### ISSUE TITLE
sorting folders by name + bookmarks by date

### ISSUE THREAD

**Issue by clown200knax** [antoyo/auto-sort-bookmarks#10]
First and foremost thank you Antoyo for this wonderful add-on.

Would be amazing if you could add the feature that different bookmark types (folders, bookmarks, smart...) can be sorted differently.

ex. Folders (at the top) sorted by name - Bookmarks sorted by date.

Please let me know

**Comment by antoyo** [comment]
This add-on needs a complete rewrite.
I'll add this feature and other requested features when I rewrite it.
I'll try to do it this summer.

**Comment by clown200knax** [comment]
I couldn't ask for more.
Would appreciate if you could let me know then.

**Comment by clown200knax** [comment]
Hello antoyo,

any updates from your side on this one?

Please let me know

**Comment by antoyo** [comment]
No, sorry.
I'm quite busy these days and, as I don't use Firefox anymore, this is not in my priorities.
By the way, Mozilla is quite slow to approve a rewrite of another of my add-on :
https://addons.mozilla.org/en-us/firefox/addon/down-for-everyone-or-just-me/versions/
I used another language than JavaScript, as I intented to do with Auto-Sort Bookmarks (ASB), and it seems to cause some issues for the review (obfuscated JavaScript…). If they don't approve it, I believe I won't rewrite ASB soon.

**Comment by Gitoffthelawn** [comment]
If the AMO editor is thinking you are obfuscating JavaScript, when you are really just using another language, you can politely point that out and ask for a reviewer that is knowledgeable in the language you used.  They should be very willing to comply with your simple and reasonable request.

**Comment by antoyo** [comment]
That's what they thought at the beginning.
So, I replied to explain the situation (more than one month ago) and I added the [original source code on GitHub](https://github.com/antoyo/down-for-everyone-or-just-me) with build instructions.
But I did not get any reply.

**Comment by Gitoffthelawn** [comment]
Sorry to hear that happened to you.  Try again.  They sometimes lose messages or get behind on projects.  They will likely have to assign your extensions to a reviewer who understands OCaml.  It's a pretty straightforward language, so even if they don't have an expert, they should be able to understand the general idea.

BTW, what got you using OCaml?

**Comment by antoyo** [comment]
I've just sent another email and a post on IRC: I'll see what will happen.

I switch to OCaml because some users got bugs that I cannot reproduce on my computer and I hope that Auto-Sort Bookmarks will be more robust written in a strongly/statically typed language. Also, I like this programming language for being concise, modular, functional and strongly/statically typed.

**Comment by Gitoffthelawn** [comment]
Sounds great!  Hopefully they will get it done.

OCaml has many wonderful benefits.  I agree with everything you said!

**Comment by clown200knax** [comment]
Hi antoyo & Gitoffthelawn,

If both bookmarks could be sorted by date combinted with folders sorted by name, this would definitely be a 5-star FF add-on. The user numbers would go trough the roof.

Thank you for your work.

**Comment by antoyo** [comment]
This feature has been added in version 2.8.
