### ISSUE TITLE
v2.8: at addons.mozilla.org/en-US/firefox/

### ISSUE THREAD

**Issue by clown200knax** [antoyo/auto-sort-bookmarks#14]
Hi Antoyo,

The release of v2.8 are wonderful news.

Can we assume that v2.8 will soon be available as a FF plug-in.
Does Mozilla currently review v2.8?

Thanks

**Comment by antoyo** [comment]
Yes, it is in review. You can download it now in the [version page](https://addons.mozilla.org/en-US/firefox/addon/auto-sort-bookmarks/versions/).
