### ISSUE TITLE
bookmark toolbar: sorting can't be disabled

### ISSUE THREAD

**Issue by clown200knax** [antoyo/auto-sort-bookmarks#16]
Even the checkbox for bookmark toolbar is unchecked,
the bookmark toolbar gets sorted.

The plugin still deserves 10 stars **********

**Comment by antoyo** [comment]
I've just tried and everything seems to be ok.
Have you checked the Recursive checkbox next to Bookmark toolbar as well?
It means that no bookmarks in the folder will be sorted.
If this checkbox is not checked, the bookmarks in the bookmark toolbark folders (sub-folders) will be sorted.
If you checked this checkbox, can you tell me when the sort happens (on Firefox startup, when adding a new bookmark)?
Do you see any errors in the Browser console (`Ctrl-Shift-J`).
Thanks for reporting this issue.

**Comment by antoyo** [comment]
Could you answer my question, please?

**Comment by clown200knax** [comment]
Followed your steps. Works fine.
