### ISSUE TITLE
Problem with addon in FF40

### ISSUE THREAD

**Issue by wtd3** [antoyo/auto-sort-bookmarks#17]
With the latest update to FF40, the Sort Folders>Configure button opens up a page that does now show the names of the folders, just check boxes on the tab that opens at : resource://sortbookmarks-at-bouanto/autosortbookmarks/data/config

**Comment by antoyo** [comment]
I cannot reproduce.
Can you send me a screen capture, please?
Do you see any errors in the browser console (`Ctrl-Shift-J`)?
Which operating system do you use?
Thanks for reporting this issue.

**Comment by wtd3** [comment]
Attached are two screenshots. FYI, I am using Windows 10 and Firefox 40 and even created a new Firefox Profile and only added this extension only, with no others at all and I am getting the same results...the page that opens up FIRST does NOT have folder descriptions next to the checkboxes and when I expand the plus signs only a few are showing folder descriptions, yet there is checkmarks in their boxes.

The previous version of your extension did not use a Sort Folders Configure button that opened an internal resource URL and worked fine with all options listed just by opening the extension and nothing that open an external resource URL and work flawlessly. Hope that a fix can be made asap.

Thanks!
![when_configure_button_is_clicked](https://cloud.githubusercontent.com/assets/13759028/9239837/88078c66-412d-11e5-8c19-5e2a89564a68.PNG)
![when_plusmarks_are_expanded](https://cloud.githubusercontent.com/assets/13759028/9239839/8e69d582-412d-11e5-8f84-bc9b5ef744b5.PNG)

**Comment by antoyo** [comment]
I confirm this bug:
it happens when using a language that the add-on does not provide translations for.
In this case, it should default to english.

**Comment by wtd3** [comment]
Meaning, when you say confirm, that language bug, is causing my issues?  




-------- Original Message --------

**Comment by antoyo** [comment]
Yes.
I'm currently working to fix this issue.

**Comment by wtd3** [comment]
Great! Thanks a lot!!




-------- Original Message --------

**Comment by antoyo** [comment]
Just to make sure I've fixed the bug correctly, can you tell me the language of your Firefox?
Currently, this add-on has translations for french, german and english.
For any other language, the text in english should be displayed.

Can you also go to this URL to check if you see the text on the buttons:
```
resource://sortbookmarks-at-bouanto/autosortbookmarks/data/confirmation.html
```
?
Do not click on the buttons if you do not see their text since it may change the autosort option.
Thanks.

**Comment by wtd3** [comment]
My Firefox language is English/United States [en-us]. The URL you provide brings up a page that asks me if I want to enable the autosort. I did not click on anything there.




-------- Original Message --------

**Comment by antoyo** [comment]
This is strange. It should work when using the english locale.
I tested on Windows 10 and did not see this issue.
I made a new version that may fix this issue.
Could you try [version 2.9](https://addons.mozilla.org/en-us/firefox/addon/auto-sort-bookmarks/versions/) to see if this fixes this issue, please?
For your information, this is what you should see:
![screencapture](https://cloud.githubusercontent.com/assets/584972/9265078/1c8508cc-41fc-11e5-9b0c-c83b11089edd.png)

**Comment by antoyo** [comment]
Did the version 2.9 fix this issue?

**Comment by wtd3** [comment]
Hi,

Check your inbox dated August 13. I replied telling you that v2.9 worked. Not sure if you got my reply? 

Anyway, yes v2.9 works!! Thank you!!!

When will it be signed by Firefox?

Billy




-------- Original Message --------

**Comment by antoyo** [comment]
Hi.
I did not receive your reply.
According to [MozillaWiki](https://wiki.mozilla.org/Addons/Extension_Signing), "We automatically signed reviewed versions of all add-ons currently hosted on AMO. All new versions will be signed automatically after they pass review.", so I believe it takes some time to sign the add-on.
Please consider updating your rating on https://addons.mozilla.org/
Thanks again for reporting this issue.

**Comment by antoyo** [comment]
I asked the question to Mozilla and add-ons are automatically signed when they are fully reviewed, so I was wrong: the add-on is already signed.

**Comment by hugotheboss65** [comment]
I think, that the problem is due to running Firefox in "private browsing mode" (Menu / Options / Privacy / private browsing mode = On) resp. opening a window (Menu / New Private Window).
You have to disable private browsing mode, press the configure button, exclude folders from sorting and the reactivate private browsing mode - if you like so ...
