### ISSUE TITLE
[Bug] Folders listed twice during first run

### ISSUE THREAD

**Issue by Gitoffthelawn** [antoyo/auto-sort-bookmarks#18]
Excellent extension!  Amazing!  Thank you!

The first time I installed it, the top level folders within the Bookmarks Menu section were duplicated in the `Folders to Sort` configuration screen.

When I clicked the `+` to expand the Bookmarks Menu items, it did not respond immediately, so I pressed the `+` several times.  I'm not sure if that had anything to do with causing the issue.

The workaround was simply to close the configuration tab and reopen it.  After that, everything worked amazingly well.

Version tested: 2.9 on Firefox 40.0.2

**Comment by antoyo** [comment]
I confirm this bug.
This will be fixed in the next version.
Thanks for reporting it.

**Comment by Gitoffthelawn** [comment]
You're welcome.  I'm glad you were able to confirm it.  Thanks for the great extension.

**Comment by antoyo** [comment]
Version 2.10 fixes this issue and improves the performance of this page.
