### ISSUE TITLE
Nothing gets sorted

### ISSUE THREAD

**Issue by gene-pavlovsky** [antoyo/auto-sort-bookmarks#20]
FF 40.0.2, I just noticed the auto-sort no longer works.
I have auto sorting disabled and instead use the toolbar button to run this plug-in. When I do, nothing happens - the bookmark folders inside Bookmark menu (it's checked in "sort folders" list) don't get sorted. Nothing in the browser console.

**Comment by antoyo** [comment]
It works on my side.
Do have you thousands of bookmarks? If yes, it can be at bit slower to sort them.
Which version of the add-on do you use?
Is it working with an older version?
Thanks for reporting the issue.

**Comment by gene-pavlovsky** [comment]
I've got the 2.10 version of the add-on and over 2000 bookmarks.
I just noticed a strange thing - if I mess up the sort order of the
bookmark folders I've had before, then use the add-on, sort order is
restored. However there are two new bookmark folders I've added just
recently, they stay at the bottom of the bookmarks menu (right after
recently bookmarked) - they don't get sorted. But strangely after I dragged
them up somewhere, then sorted again, they got sorted. Why is that zone at
the end of bookmarks menu excluded from sorting? Picture illustration
attached, the "TODO" folder is the one not getting sorted, moving it above
"most visited" manually then sorting and it works.
--Gene

**Comment by antoyo** [comment]
@gene-pavlovsky This is perfectly normal. Look at the option "Delay for Folders".
This option exists to allow you to rename the folder before it gets sorted.

**Comment by gene-pavlovsky** [comment]
Delay is set to 30. 30 what? Can you explain what this option does, exactly?

**Comment by antoyo** [comment]
This is 30 seconds. This means that the folders will be sorted after 30 seconds (so that you have the time to rename a folder after creating one; otherwise, you will create a new folder and it will get sorted before you have the time to do so).
I suggest you to read the section [About this Add-on on this page][1] or the [readme][2] for more information.

[1]: https://addons.mozilla.org/en-us/firefox/addon/auto-sort-bookmarks/
[2]: https://github.com/antoyo/auto-sort-bookmarks#readme

**Comment by gene-pavlovsky** [comment]
Thank you. Appreciate your help. I still don't understand, why these
folders only got sorted after I moved them up higher than "Most visited,
Recent Tags, Recently bookmarked" ?  (see screenshot 2 e-mails ago).

**Comment by eric-bixby** [comment]
I think this issue is OBE (overcome by events).  I'm not able to reproduce it.  If you still see the same problem in the latest release (2.10.7), then open a new issue.
