### ISSUE TITLE
Maintain auto-sort-bookmarks

### ISSUE THREAD

**Issue by lwb78750** [antoyo/auto-sort-bookmarks#25]
Hello... I'm a Senior Software Engineer in Austin Texas with over 25 years of experience. I have been wanting to develop a Firefox Extension for some time now. I use and quite like auto-sort-bookmarks, and I think taking on your existing extension would be a great way to start. I'm primarily a C++/Qt/OOP/Embedded Systems  Guy, but I also do a fair amount of JavaScript, among other things.

Please get back to me via email if you think this might work for you. *** I get a lot of email, so please make the subject line one that I will readily notice. :-)

Thanks,
Lance B.
Austin, Texas

**Comment by antoyo** [comment]
Hello.
I do not have your email, so I'll answer here.

I made this [wiki page][1] to provide you all information you need about the design decisions and process of this add-on.
Please read this page first.

If you are still interested, I'll add you as a contributor.

If you have experience in profiling, [this issue][2] is the most critical to fix right now.
There are also other [issues][4] to fix and enhancement requests.

As you can see [here][3], other people are interested to maintain this add-on. Perhaps you could communicate with them coordinate your efforts.

If you have any question, feel free to ask.
Thanks for your interest.

[1]: https://github.com/antoyo/auto-sort-bookmarks/wiki/Information-for-future-mainteners
[2]: https://github.com/antoyo/auto-sort-bookmarks/issues/19
[3]: https://github.com/antoyo/auto-sort-bookmarks/issues/23
[4]: https://github.com/antoyo/auto-sort-bookmarks/issues
