### ISSUE TITLE
Fix to make it work with Multi-process Firefox

### ISSUE THREAD

**Issue by antoyo** [antoyo/auto-sort-bookmarks#26]
As this add-on relies on low-level APIs and open tabs, it is likely to stop working in multi-process Firefox.

If someone could look at this, it would be nice.

**Comment by Gitoffthelawn** [comment]
When do you think multi-process will actually hit release?

**Comment by TheRealMarnes** [comment]
@Gitoffthelawn they say the first quarter of 2016 but it's not like they've ever been on time with it

@antoyo using the sdk already makes most code fairly e10s safe (i.e. open tabs and such is not a problem), but yes it still needs to be checked

I'd do it myself but my job is taking such a chunk out of my time I'm barely getting my personal projects done, let alone I'd have the time to work on this one :/

**Comment by eric-bixby** [comment]
This issue has been resolved.
