### ISSUE TITLE
Toolbar button no longer works

### ISSUE THREAD

**Issue by Gitoffthelawn** [antoyo/auto-sort-bookmarks#28]
With Auto Sort Bookmarks 2.10.4 on Firefox 45.0.1, the Auto Sort Bookmarks toolbar button no longer works.  Pressing the button does not result in any action being taken.

**Comment by eric-bixby** [comment]
This is working for me in Firefox 47.0.1.  Do you still see the problem after upgrading?

**Comment by Gitoffthelawn** [comment]
@eric-bixby I'll check it for you as soon I get to a test system.

**Comment by rek769** [comment]
I installed Auto-Sort Bookmarks v2.10.4 on Firefox v47.0.1 I. There was no version of Auto-Sort Bookmarks installed before.

The toolbar button does not even show up anywhere I can find. Not on the Toolbar. Not in the Additional Tools and Features section of the Customize Firefox page. not on the menus in the Bookmarks window.

Where should the toolbar button show up?

**Comment by eric-bixby** [comment]
Did you try clicking on "Restore Defaults" on the Customize Firefox page?  Sometimes this works, but you'll have to reapply your customization.  If it works, it should show up under the Additional Tools and Features section.

**Comment by Gitoffthelawn** [comment]
@eric-bixby As promised, I just tested the toolbar button.  It now works perfectly on the Firefox 47.0.1.  :-)
