### ISSUE TITLE
sorting clashes with syncing and corrupts bookmark file

### ISSUE THREAD

**Issue by ineuw** [antoyo/auto-sort-bookmarks#35]
You must allow user control for a single sort action, and must not sort automatically when a bookmark is added or deleted, and especially at startup. My bookmark file corrupted and it was traced to this add-on. 
I was using FF v48

**Comment by eric-bixby** [comment]
It has that feature. Disable the auto-sort option and click on the add-on's
icon in the toolbar to sort manually.

**Comment by ineuw** [comment]
Thanks, I misunderstood the information provided with the add-on.
