### ISSUE TITLE
Reduce Blocking/Freezing when Sorting a lot of Bookmarks

### ISSUE THREAD

**Issue by eric-bixby** [antoyo/auto-sort-bookmarks#36]
@digitalcircuit wrote:

> Testing via the "Load Temporary Addon" option in about:debugging#addons, the new version does successfully complete sorting. All of Firefox freezes for 5-15 second-long intervals, making any interaction almost impossible until the sorting finishes (takes about 1 minute), but it does complete and does not trigger the "unresponsive script" warning.
> 
> Certainly improves the situation, but still more impactful on the UI than 2.10.5.
> 
> After trying again, the hangs only appear to happen when there's a lot of bookmarks to sort. When there's nothing to sort, or only 1 or 2 bookmarks, it's fairly quick. Firefox hangs in a similar way (edit: without affecting the entire UI, just bookmark management) when adding/removing bookmarks, so I'm not sure this is the fault of the addon.
> 
> 2.10.7 seems to be a definite improvement over 2.10.6 in either case.

**Comment by digitalcircuit** [comment]
Thanks for opening a new bug!  Pardon for not doing that sooner since this isn't directly related to auto-sorting causing CPU issues.

**Comment by michaelalandover** [comment]
If you want power you have to do maintenance and you can't complain. If you want to sports car you can't expect not to have to do maintenance on. I am trying to get used to the waits as I have thousands of bookmarks

Thank you for all your work

Sent from my iPhone

On Sep 10, 2016, at 3:10 PM, Eric Bixby <notifications@github.com<mailto:notifications@github.com>> wrote:


@digitalcircuit<https://github.com/digitalcircuit> wrote:

Testing via the "Load Temporary Addon" option in about:debugging#addons, the new version does successfully complete sorting. All of Firefox freezes for 5-15 second-long intervals, making any interaction almost impossible until the sorting finishes (takes about 1 minute), but it does complete and does not trigger the "unresponsive script" warning.

Certainly improves the situation, but still more impactful on the UI than 2.10.5.

After trying again, the hangs only appear to happen when there's a lot of bookmarks to sort. When there's nothing to sort, or only 1 or 2 bookmarks, it's fairly quick. Firefox hangs in a similar way (edit: without affecting the entire UI, just bookmark management) when adding/removing bookmarks, so I'm not sure this is the fault of the addon.

2.10.7 seems to be a definite improvement over 2.10.6 in either case.

-

**Comment by heliocarbex** [comment]
Hello Guys,

just for your knowledge: the 2.10.7 version continues with the freeze problem. Firefox 49.0.1, Windows 10 Home.

**Comment by eric-bixby** [comment]
OK, I'll try making another update.

**Comment by eric-bixby** [comment]
Here's a quick report to let you know what's going on...  I haven't forgotten about this.

I'm currently reading "Async JavaScript" by Trevor Burnham:
https://pragprog.com/book/tbajs/async-javascript

I mostly do Java work, so I'm trying to adjust my thinking to the JavaScript way (JavaScript is not Java).  I know the setTimeout() technique works, but I'm also experimenting with "promises".

Worse case, I'll revert back to using the generators/yield approach.

**Comment by eric-bixby** [comment]
I've posted version 2.10.8 to Mozilla for review or you can try the unsigned version here:
https://github.com/antoyo/auto-sort-bookmarks/releases/tag/v2.10.8

I tested this with 3000 random bookmarks (3 folders with 1000 each).  I didn't notice UI blocking during the sorting.  However, your results may vary.

Also, the browser/UI may block during certain operations that are not controlled by the add-on.  For example, when I import 3000 bookmarks, I see the wait-cursor (hour-glass).  I also get the wait-cursor when viewing the list of bookmarks for the first-time after importing (I think Firefox is indexing the database or something so this takes some time).

**Comment by michaelalandover** [comment]
Thanks
Have started using www.bookmarkos.com
Sorts within folders
It doesn't have RSS feed's but it does allow you to store same bookmarks in one place and access from all browsers. It uses bookmarklet's to make it easy to save bookmarks in commonly used foldersit is much like the old blinkpro.com but the danger of coarse is if it goes down or out of business you could lose your bookmarks if you don't back them up regularly. And of privacy is a concern somebody else there can see your bookmarks
Mike

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by eric-bixby** [comment]
Closing issue in favor of issue #39.
