### ISSUE TITLE
Auto-Sort Bookmarks 2.10.8 freezes browser.

### ISSUE THREAD

**Issue by ivysrono** [antoyo/auto-sort-bookmarks#39]
Auto-Sort Bookmarks 2.10.8
Firefox 49.0.2 x64
win10 x64

Everytime I open one new tab.

**Comment by DemonAk** [comment]
Yes, and I was terribly slow down when you open the page. So far, the disabled

**Comment by eric-bixby** [comment]
Opening a tab or page should have nothing to do with the add-on.  Unless it's still sorting when you do these things.

@DemonAk I guessing you are using Win10 with the latest Firefox also.

It shouldn't matter, but I primarily use MacOS.  I'll try on a virtual Win10 and see if I get the same results.

**Comment by eric-bixby** [comment]
To help with debugging:
1) Did you restart Firefox after updating the add-on?
2) Do you try disabling the other add-ons?
3) How fast of computer do you use?  i.e., Quad-core 4GHz? (shouldn't matter, just curious)
4) Amount how many bookmarks do you have? (in case I need to increase my test case)

**Comment by DemonAk** [comment]
You right, i am using win10x64 latest, firefox x64 49.02
previosly version asb worked fine
1. yes
2. no, disabled only latest addon update
3. my specs: amd fx8350@4.5, 32gb ram
4. bookmarks: i think 100+

**Comment by eric-bixby** [comment]
I've confirmed this bug on Windows and Linux, less obvious on my mac, but Mac also.

**Comment by MaxFrames** [comment]
I have the same issue on Windows 7 x64, FF 49.0.2. For some reason, I don't seem to have the issue on Windows 10 x64, FF 49.0.2. It started when the new version of the addon was installed. If I uninstall the addon, all is fine. Hope it gets fixed, the addon was great.

**Comment by EMLVIRUS** [comment]
Strange enough. This bug seems not reproducible on Firefox 50beta, Windows 10 x64 latest.

**Comment by eric-bixby** [comment]
I now have a test-bed of Win 7 x64, Win10 x64, MacOS 10.12, and LinuxMint (Ubuntu/Debian) with FF 49.0.2.  I've narrowed it down to where the freezing is occurring.  The strange part is that this code wasn't changed.  Therefore, it must be a side-effect of my changes.

Also, previously, I was developing and testing with Firefox Developer Edition and it's less noticeable.  You might get different results with a different version of FF, but it also depends on how long it takes to sort (the longer it takes to sort, the more noticeable the freezing is).

**Comment by eric-bixby** [comment]
It appears the freezing is in the Firefox API (which I have no control over).  In my local version, I was able to decrease the freezing but not eliminate it.  The freezing happens (for me) in the previous versions also but its most noticeable in v2.10.8.  I'm thinking of adding some kind of indicator so you know when it's sorting and when it's not; if you know when to expect the delay it might be less annoying.

**Comment by eric-bixby** [comment]
@EMLVIRUS good tip, I just tried FF 50beta (which auto-updated to 50), I did not see freezing during sorting.

**Comment by jmwoods301** [comment]
"It appears the freezing is in the Firefox API (which I have no control over). In my local version, I was able to decrease the freezing but not eliminate it. "

So version 2.10.7 works fine (no delays) in Firefox 49.0.2, but 2.10.8 locks it up entirely on my Win 7 Pro system.

Whatever changed in version 2.10.8 is causing the issue.

**Comment by eric-bixby** [comment]
Please try version 2.10.9, and let me know if this fixes the problem for you or not:
https://github.com/antoyo/auto-sort-bookmarks/releases/tag/v2.10.9

This is an unsigned release, so you'll need to type "about:debugging" in the address bar, select "Load Temporary Add-on", and then select the saved add-on from the link above.

**Comment by jmwoods301** [comment]
Version 2.10.9 (labeled 2.10.8 in the Firefox add-on description) fixed the issue for me.

**Comment by eric-bixby** [comment]
I fixed the label (if you re-download/install it says 2.10.9 now).  I also posted this to Mozilla for review.
