### ISSUE TITLE
Browser crash on startup

### ISSUE THREAD

**Issue by mattsplats** [antoyo/auto-sort-bookmarks#44]
Just today my Firefox is crashing on startup every time.  After loading in Safe Mode and enabling addons one-by-one, I have found Auto-Sort to be the culprit.  When enabled, Firefox crashes on startup; disabled, all is normal.  In fact, just clicking Enable causes Firefox to crash instantly!  I have not had issues in the past and have had auto-sort enabled.

Many thanks for this great add-on, I'll be glad to provide any assistance diagnosing this that I can (crash logs, etc.).  I was looking through recent commits to master and the only changes I see are for localization - is it just me or does that sound like an unlikely culprit?

**Comment by defmonk0** [comment]
Having the same issue as of today. As Matt said, if any assistance is needed for diagnosis, let me know what you need.

**Comment by eric-bixby** [comment]
There seems to be a problem with the following Firefox JavaScript for the zh-CN.properties file:
https://addons.cdn.mozilla.net/en-US/firefox/jsi18n.js

If someone could post a Mozilla Crash Report that would help with my analysis.

**Comment by mattsplats** [comment]
AdapterDeviceID: 0x13c2
AdapterDriverVersion: 21.21.13.7866
AdapterSubsysID: 00000000
AdapterVendorID: 0x10de
Add-ons: %7B75CEEE46-9B64-46f8-94BF-54012DE155F0%7D:0.4.15,sendtokindle%40amazon.com:1.0.2.76,contextsearch2%40lwz.addons.mozilla.org:0.4.6.26,support%40lastpass.com:3.3.2,%7Bdc572301-7619-498c-a57d-39143191b318%7D:0.5.0.2,%7B73a6fe31-595d-460b-a920-fcc0f8843232%7D:2.9.5.3,%7Be4a8a97b-f2ed-450b-b12d-ee082ba24781%7D:3.9,xseei%40nohamelin:0.3.2,https-everywhere-eff%40eff.org:5.2.11,ClassicThemeRestorer%40ArisT2Noia4dev:1.6.2.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:51.0.1,%7B65e41d20-f092-41b7-bb83-c6e8a9ab0f57%7D:1.2.6,%7Bd10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d%7D:2.8.2,diagnostics%40mozilla.org:1.0,disableSHA1rollout%40mozilla.org:1.2,hsts-priming%40mozilla.org:1.0,e10srollout%40mozilla.org:1.7,firefox%40getpocket.com:1.0.5,webcompat%40mozilla.org:1.0,aushelper%40mozilla.org:1.0,firefox%40betterttv.net:6.8.5,%7B1280606b-2510-4fe0-97ef-9b5a22eafe30%7D:0.8.1.13,jid1-F8tBtAByBTmYCw%40jetpack:0.1-alpha.1-signed.1-signed,sortbookmarks%40bouanto:2.10.10
AddonsShouldHaveBlockedE10s: 1
AvailablePageFile: 14408380416
AvailablePhysicalMemory: 11665145856
AvailableVirtualMemory: 2978500608
BIOS_Manufacturer: American Megatrends Inc.
BlockedDllList: 
BreakpadReserveAddress: 99155968
BreakpadReserveSize: 67108864
BuildID: 20170125094131
CPUMicrocodeVersion: 0x1e
ContentSandboxCapable: 1
ContentSandboxLevel: 1
CrashTime: 1487534889
E10SCohort: disqualified-test
EMCheckCompatibility: true
EventLoopNestingLevel: 1
FramePoisonBase: 00000000f0de0000
FramePoisonSize: 65536
InstallTime: 1485713406
Notes: AdapterVendorID: 0x10de, AdapterDeviceID: 0x13c2, AdapterSubsysID: 00000000, AdapterDriverVersion: 21.21.13.7866
FP(D00-L1000-W00001000-T0000) D2D1.1? DWrite? DWrite+ D2D1.1+ D3D11 Layers? D3D11 Layers+ 
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: release
SafeMode: 0
SecondsSinceLastCrash: 4515
StartupCrash: 0
StartupTime: 1487530466
SystemMemoryUsePercentage: 31
TelemetryEnvironment: {"build":{"applicationId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","applicationName":"Firefox","architecture":"x86","buildId":"20170125094131","version":"51.0.1","vendor":"Mozilla","platformVersion":"51.0.1","xpcomAbi":"x86-msvc","hotfixVersion":"20160826.01"},"partner":{"distributionId":null,"distributionVersion":null,"partnerId":null,"distributor":null,"distributorChannel":null,"partnerNames":[]},"system":{"memoryMB":16338,"virtualMaxMB":4096,"cpu":{"count":4,"cores":4,"vendor":"GenuineIntel","family":6,"model":60,"stepping":3,"l2cacheKB":256,"l3cacheKB":6144,"speedMHz":3492,"extensions":["hasMMX","hasSSE","hasSSE2","hasSSE3","hasSSSE3","hasSSE4_1","hasSSE4_2","hasAVX","hasAVX2"]},"os":{"name":"Windows_NT","version":"10.0","locale":"en-US","servicePackMajor":0,"servicePackMinor":0,"windowsBuildNumber":14393,"windowsUBR":693,"installYear":2016},"hdd":{"profile":{"model":"OCZ-AGILITY4","revision":"1.5.2"},"binary":{"model":"OCZ-AGILITY4","revision":"1.5.2"},"system":{"model":"OCZ-AGILITY4","revision":"1.5.2"}},"gfx":{"D2DEnabled":false,"DWriteEnabled":true,"ContentBackend":"Direct2D 1.1","adapters":[{"description":"NVIDIA GeForce GTX 970","vendorID":"0x10de","deviceID":"0x13c2","subsysID":"00000000","RAM":4096,"driver":"C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_0cc477a6fec64d8c\\nvd3dumx,C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_0cc477a6fec64d8c\\nvwgf2umx,C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_0cc477a6fec64d8c\\nvwgf2umx,C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_0cc477a6fec64d8c\\nvwgf2umx C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_0cc477a6fec64d8c\\nvd3dum,C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_0cc477a6fec64d8c\\nvwgf2um,C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_0cc477a6fec64d8c\\nvwgf2um,C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\nv_dispi.inf_amd64_0cc477a6fec64d8c\\nvwgf2um","driverVersion":"21.21.13.7866","driverDate":"2-9-2017","GPUActive":true}],"monitors":[{"screenWidth":1920,"screenHeight":1200,"refreshRate":59,"pseudoDisplay":false},{"screenWidth":1200,"screenHeight":1920,"refreshRate":59,"pseudoDisplay":false}],"features":{"compositor":"d3d11","d3d11":{"status":"available","version":45312,"warp":false,"textureSharing":true,"blacklisted":false},"d2d":{"status":"available","version":"1.1"}}},"isWow64":true},"settings":{"blocklistEnabled":true,"e10sEnabled":false,"e10sCohort":"disqualified-test","telemetryEnabled":true,"locale":"en-US","update":{"channel":"release","enabled":true,"autoDownload":true},"userPrefs":{"browser.cache.disk.capacity":358400,"browser.formfill.enable":false,"browser.newtabpage.enhanced":false,"browser.startup.homepage":"<user-set>","browser.urlbar.suggest.searches":true,"browser.urlbar.userMadeSearchSuggestionsChoice":true,"dom.max_script_run_time":40},"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":true,"defaultSearchEngine":"google-nocodes","defaultSearchEngineData":{"name":"Google","loadPath":"jar:[app]/omni.ja!browser/google-nocodes.xml","origin":"default","submissionURL":"https://www.google.com/search?q=&ie=utf-8&oe=utf-8"}},"profile":{"creationDate":16391},"addons":{"activeAddons":{"{65e41d20-f092-41b7-bb83-c6e8a9ab0f57}":{"blocklisted":false,"description":"Allows you to schedule messages to be sent or returned at a later date.","name":"Boomerang for Gmail","userDisabled":false,"appDisabled":false,"version":"1.2.6","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16602,"updateDay":16676,"signedState":1,"isSystem":false},"jid1-F8tBtAByBTmYCw@jetpack":{"blocklisted":false,"description":"Bypass the \"You are leaving Steam\" notice when clicking on links in Steam chat.","name":"Steam Linkfilter Bypass","userDisabled":false,"appDisabled":false,"version":"0.1-alpha.1-signed.1-signed","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16391,"updateDay":16919,"signedState":2,"isSystem":false},"{75CEEE46-9B64-46f8-94BF-54012DE155F0}":{"blocklisted":false,"description":"Draw out a ruler to get the pixel width and height of any elements on a webpage.","name":"MeasureIt","userDisabled":false,"appDisabled":false,"version":"0.4.15","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":17004,"updateDay":17004,"signedState":2,"isSystem":false},"sendtokindle@amazon.com":{"blocklisted":false,"description":"Send web content such as blog posts and news articles to your Kindle devices and reading apps for re","name":"Send to Kindle for Mozilla Firefox","userDisabled":false,"appDisabled":false,"version":"1.0.2.76","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":17042,"updateDay":17042,"signedState":2,"isSystem":false},"contextsearch2@lwz.addons.mozilla.org":{"blocklisted":false,"description":"Enhances the context menu with a list of search engines and specified engines placed outside the sub","name":"Context Search X","userDisabled":false,"appDisabled":false,"version":"0.4.6.26","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":17113,"updateDay":17113,"signedState":2,"isSystem":false},"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}":{"blocklisted":false,"description":"Ads were yesterday!","name":"Adblock Plus","userDisabled":false,"appDisabled":false,"version":"2.8.2","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16391,"updateDay":17128,"signedState":2,"isSystem":false},"support@lastpass.com":{"blocklisted":false,"description":"Last Password you will ever need","name":"LastPass","userDisabled":false,"appDisabled":false,"version":"3.3.2","scope":1,"type":"extension","foreignInstall":true,"hasBinaryComponents":false,"installDay":16391,"updateDay":17168,"signedState":2,"isSystem":false},"{dc572301-7619-498c-a57d-39143191b318}":{"blocklisted":false,"description":"Tab browsing with an added boost.","name":"Tab Mix Plus","userDisabled":false,"appDisabled":false,"version":"0.5.0.2","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16391,"updateDay":17183,"signedState":2,"isSystem":false},"{73a6fe31-595d-460b-a920-fcc0f8843232}":{"blocklisted":false,"description":"Extra protection for your Firefox: NoScript allows JavaScript, Java (and other plugins) only for tru","name":"NoScript","userDisabled":false,"appDisabled":false,"version":"2.9.5.3","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16391,"updateDay":17186,"signedState":2,"isSystem":false},"{e4a8a97b-f2ed-450b-b12d-ee082ba24781}":{"blocklisted":false,"description":"A User Script Manager for Firefox","name":"Greasemonkey","userDisabled":false,"appDisabled":false,"version":"3.9","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":17193,"updateDay":17193,"signedState":2,"isSystem":false},"firefox@betterttv.net":{"blocklisted":false,"description":"Enhances Twitch with new features, bug fixes, and reduced clutter.","name":"BetterTTV","userDisabled":false,"appDisabled":false,"version":"6.8.5","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":17193,"updateDay":17193,"signedState":1,"isSystem":false},"e10srollout@mozilla.org":{"blocklisted":false,"description":"Staged rollout of Firefox multi-process feature.","name":"Multi-process staged rollout","userDisabled":false,"appDisabled":false,"version":"1.7","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16927,"updateDay":17195,"isSystem":true},"firefox@getpocket.com":{"blocklisted":false,"description":"When you find something you want to view later, put it in Pocket.","name":"Pocket","userDisabled":false,"appDisabled":false,"version":"1.0.5","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16927,"updateDay":17195,"isSystem":true},"webcompat@mozilla.org":{"blocklisted":false,"description":"Urgent post-release fixes for web compatibility.","name":"Web Compat","userDisabled":false,"appDisabled":false,"version":"1.0","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":17067,"updateDay":17195,"isSystem":true},"aushelper@mozilla.org":{"blocklisted":false,"description":"Sets value(s) in the update url based on custom checks.","name":"Application Update Service Helper","userDisabled":false,"appDisabled":false,"version":"1.0","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":17121,"updateDay":17195,"isSystem":true},"{1280606b-2510-4fe0-97ef-9b5a22eafe30}":{"blocklisted":false,"description":"Saves and restores the state of all windows.","name":"Session Manager","userDisabled":false,"appDisabled":false,"version":"0.8.1.13","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16391,"updateDay":17197,"signedState":2,"isSystem":false},"xseei@nohamelin":{"blocklisted":false,"description":"Import and export search engines from XML files in the OpenSearch format","name":"XML Search Engines Exporter/Importer","userDisabled":false,"appDisabled":false,"version":"0.3.2","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":17113,"updateDay":17206,"signedState":2,"isSystem":false},"https-everywhere-eff@eff.org":{"blocklisted":false,"description":"Encrypt the Web! Automatically use HTTPS security on many sites.","name":"HTTPS Everywhere","userDisabled":false,"appDisabled":false,"version":"5.2.11","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16668,"updateDay":17211,"signedState":2,"isSystem":false},"ClassicThemeRestorer@ArisT2Noia4dev":{"blocklisted":false,"description":"'Classic Theme Restorer' restores many customization features Firefox lost over time like old 'Firef","name":"Classic Theme Restorer","userDisabled":false,"appDisabled":false,"version":"1.6.2.1","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":16808,"updateDay":17214,"signedState":2,"isSystem":false},"diagnostics@mozilla.org":{"blocklisted":false,"description":"Diagnose Firefox update problems.","name":"Diagnostics","userDisabled":false,"appDisabled":false,"version":"1.0","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":17214,"updateDay":17214,"signedState":3,"isSystem":true},"disableSHA1rollout@mozilla.org":{"blocklisted":false,"description":"Staged rollout deprecating SHA-1 in certificate signatures.","name":"SHA-1 deprecation staged rollout","userDisabled":false,"appDisabled":false,"version":"1.2","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":17214,"updateDay":17214,"signedState":3,"isSystem":true},"hsts-priming@mozilla.org":{"blocklisted":false,"description":"Disables sending HSTS priming requests by default in Release.","name":"Send HSTS Priming Requests","userDisabled":false,"appDisabled":false,"version":"1.0","scope":1,"type":"extension","foreignInstall":false,"hasBinaryComponents":false,"installDay":17214,"updateDay":17214,"signedState":3,"isSystem":true}},"theme":{"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","blocklisted":false,"description":"The default theme.","name":"Default","userDisabled":false,"appDisabled":false,"version":"51.0.1","scope":4,"foreignInstall":false,"hasBinaryComponents":false,"installDay":16391,"updateDay":17195},"activePlugins":[{"name":"QuickTime Plug-in 7.7.8","version":"7.7.8.0","description":"The QuickTime Plugin allows you to view a wide variety of multimedia content in Web pages. For more ","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/sdp","application/x-sdp","application/x-rtsp","video/quicktime","video/flc","audio/x-wav","audio/wav"],"updateDay":16672},{"name":"QuickTime Plug-in 7.7.8","version":"7.7.8.0","description":"The QuickTime Plugin allows you to view a wide variety of multimedia content in Web pages. For more ","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["audio/aiff","audio/x-aiff","audio/basic","audio/mid","audio/vnd.qcelp","audio/x-gsm","audio/amr","audio/aac"],"updateDay":16672},{"name":"QuickTime Plug-in 7.7.8","version":"7.7.8.0","description":"The QuickTime Plugin allows you to view a wide variety of multimedia content in Web pages. For more ","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["audio/x-aac","audio/x-caf","audio/x-ac3","video/x-mpeg","video/mpeg"],"updateDay":16672},{"name":"QuickTime Plug-in 7.7.8","version":"7.7.8.0","description":"The QuickTime Plugin allows you to view a wide variety of multimedia content in Web pages. For more ","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["audio/mpeg","audio/x-mpeg","video/3gpp","audio/3gpp","video/3gpp2","audio/3gpp2","video/sd-video"],"updateDay":16672},{"name":"QuickTime Plug-in 7.7.8","version":"7.7.8.0","description":"The QuickTime Plugin allows you to view a wide variety of multimedia content in Web pages. For more ","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-mpeg","video/mp4","audio/mp4","audio/x-m4a","audio/x-m4p","audio/x-m4b","video/x-m4v"],"updateDay":16672},{"name":"Adobe Acrobat","version":"15.23.20053.15062","description":"Adobe PDF Plug-In For Firefox and Netscape 15.23.20053","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/pdf","application/vnd.adobe.pdfxml","application/vnd.adobe.x-mars","application/vnd.fdf","application/vnd.adobe.xfdf","application/vnd.adobe.xdp+xml","application/vnd.adobe.xfd+xml"],"updateDay":17158},{"name":"VLC Web Plugin","version":"2.2.4.0","description":"VLC media player Web Plugin","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["audio/mp1","audio/mp2","audio/mp3","audio/mpeg","audio/mpg","audio/x-mp1","audio/x-mp2","audio/x-mp3","audio/x-mpeg","audio/x-mpg","video/mpeg","video/x-mpeg","video/mp2t","video/mpeg-system","video/x-mpeg-system","video/x-mpeg2","audio/aac","audio/x-aac","audio/mp4","audio/x-m4a","audio/m4a","video/mp4","application/mpeg4-iod","application/mpeg4-muxcodetable","application/x-extension-m4a","application/x-extension-mp4","video/x-m4v","video/mp4v-es","audio/x-pn-windows-acm","video/divx","video/msvideo","video/vnd.divx","video/x-avi","video/x-msvideo","application/ogg","video/ogg","audio/ogg","application/x-ogg","video/x-ogm+ogg","video/x-theora+ogg","video/x-theora","audio/x-vorbis+ogg","audio/x-vorbis","audio/x-speex","audio/ogg;codecs=opus","audio/opus","application/x-vlc-plugin","audio/x-ms-asf","audio/x-ms-asx","audio/x-ms-wax","video/x-ms-asf","video/x-ms-asf-plugin","video/x-ms-asx","video/x-ms-asf-plugin","video/x-ms-asf","application/x-mplayer2","video/x-ms-wm","video/x-ms-wmv","video/x-ms-wmx","video/x-ms-wvx","audio/x-ms-wma","application/x-google-vlc-plugin","audio/wav","audio/x-wav","audio/x-pn-wav","audio/x-pn-au","video/3gp","audio/3gpp","video/3gpp","audio/3gpp2","video/3gpp2","video/fli","video/flv","video/x-flc","video/x-fli","video/x-flv","application/x-matroska","video/x-matroska","audio/x-matroska","application/xspf+xml","audio/mpegurl","audio/x-mpegurl","audio/scpls","audio/x-scpls","text/google-video-pointer","text/x-google-video-pointer","video/vnd.mpegurl","application/vnd.apple.mpegurl","application/vnd.ms-asf","application/vnd.ms-wpl","application/sdp","audio/dv","video/dv","audio/x-aiff","audio/x-pn-aiff","video/x-anim","video/webm","audio/webm","application/ram","application/vnd.rn-realmedia-vbr","application/vnd.rn-realmedia","audio/vnd.rn-realaudio","audio/x-pn-realaudio-plugin","audio/x-pn-realaudio","audio/x-real-audio","audio/x-realaudio","video/vnd.rn-realvideo","audio/amr-wb","audio/amr","audio/amr-wb","audio/amr","application/x-flac","audio/x-flac","audio/flac","application/x-flash-video","application/x-shockwave-flash","audio/ac3","audio/eac3","audio/basic","audio/midi","audio/vnd.dts.hd","audio/vnd.dolby.heaac.1","audio/vnd.dolby.heaac.2","audio/vnd.dolby.mlp","audio/vnd.dts","audio/x-ape","audio/x-gsm","audio/x-musepack","audio/x-shorten","audio/x-tta","audio/x-wavpack","audio/x-it","audio/x-mod","audio/x-s3m","audio/x-xm","application/mxf","image/vnd.rn-realpix","misc/ultravox","video/x-nsv"],"updateDay":16953},{"name":"Google Update","version":"1.3.32.7","description":"Google Update","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-vnd.google.update3webcontrol.3","application/x-vnd.google.oneclickctrl.9"],"updateDay":17150},{"name":"NVIDIA 3D VISION","version":"7.17.13.7866","description":"NVIDIA 3D Vision Streaming plugin for Mozilla browsers","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/mozilla-3dv-streaming-plugin"],"updateDay":17206},{"name":"NVIDIA 3D Vision","version":"7.17.13.7866","description":"NVIDIA 3D Vision plugin for Mozilla browsers","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["image/jps","image/pns","image/mpo"],"updateDay":17206},{"name":"Microsoft Office 2016","version":"16.0.7571.7095","description":"The plugin allows you to have a better experience with Microsoft SharePoint","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-sharepoint","application/x-sharepoint-uc"],"updateDay":17204},{"name":"Silverlight Plug-In","version":"5.1.50901.0","description":"5.1.50901.0","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-silverlight","application/x-silverlight-2"],"updateDay":17045},{"name":"NPLastPass","version":"2.5.5.0","description":"LastPass Plugin","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-vnd-lastpass"],"updateDay":16391},{"name":"Shockwave Flash","version":"24.0.0.221","description":"Shockwave Flash 24.0 r0","blocklisted":false,"disabled":false,"clicktoplay":false,"mimeTypes":["application/x-shockwave-flash","application/futuresplash"],"updateDay":17211},{"name":"Skype Meetings App","version":"16.2.0.96","description":"Skype Meetings App","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-skypeforbusiness-plugin-16.2"],"updateDay":17031},{"name":"Zoom launcher - 3.0.1","version":"3.5.49839.509","description":"Zoom launcher - 3.0.1","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-zoom-scriptable-plugin"],"updateDay":16930},{"name":"Google Update","version":"1.3.29.1","description":"Google Update","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-vnd.google.update3webcontrol.3","application/x-vnd.google.oneclickctrl.9"],"updateDay":16773},{"name":"Citrix Online Web Deployment Plugin 1.0.0.104","version":"1.0.0.104","description":"Citrix Online App Detector Plugin","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/x-col-application-detector"],"updateDay":16589},{"name":"Google Talk Plugin","version":"5.41.3.0","description":"Version 5.41.3.0","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/googletalk"],"updateDay":16777},{"name":"Google Talk Plugin Video Renderer","version":"5.41.3.0","description":"Version 5.41.3.0","blocklisted":false,"disabled":false,"clicktoplay":true,"mimeTypes":["application/o1d"],"updateDay":16777}],"activeGMPlugins":{"gmp-gmpopenh264":{"version":"1.6","userDisabled":false,"applyBackgroundUpdates":1},"gmp-eme-adobe":{"version":"17","userDisabled":false,"applyBackgroundUpdates":1},"gmp-widevinecdm":{"version":"1.4.8.903","userDisabled":false,"applyBackgroundUpdates":1}},"activeExperiment":{},"persona":null}}
Theme: classic/1.0
Throttleable: 1
TotalPageFile: 21427032064
TotalPhysicalMemory: 17132064768
TotalVirtualMemory: 4294836224
URL: about:addons
UptimeTS: 15081.335941084
Vendor: Mozilla
Version: 51.0.1
Winsock_LSP: Hyper-V RAW : 2 : 34 : 1 : 1 : 0x20026 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 1234191b-4bf7-4ca7-86e0-dfd7c32b5445 
 MSAFD Tcpip [TCP/IP] : 2 : 2 : 1 : 6 : 0x20066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : e70f1aa0-ab8b-11cf-8ca3-00805f48a192 
 MSAFD Tcpip [UDP/IP] : 2 : 2 : 2 : 17 : 0x20609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : e70f1aa0-ab8b-11cf-8ca3-00805f48a192 
 MSAFD Tcpip [RAW/IP] : 2 : 2 : 3 : 0 : 0x20609 : 0xc : %SystemRoot%\system32\mswsock.dll :  : e70f1aa0-ab8b-11cf-8ca3-00805f48a192 
 MSAFD Tcpip [TCP/IPv6] : 2 : 23 : 1 : 6 : 0x20066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : f9eab0c0-26d4-11d0-bbbf-00aa006c34e4 
 MSAFD Tcpip [UDP/IPv6] : 2 : 23 : 2 : 17 : 0x20609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : f9eab0c0-26d4-11d0-bbbf-00aa006c34e4 
 MSAFD Tcpip [RAW/IPv6] : 2 : 23 : 3 : 0 : 0x20609 : 0xc : %SystemRoot%\system32\mswsock.dll :  : f9eab0c0-26d4-11d0-bbbf-00aa006c34e4 
 RSVP TCPv6 Service Provider : 2 : 23 : 1 : 6 : 0x22066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 RSVP TCP Service Provider : 2 : 2 : 1 : 6 : 0x22066 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 RSVP UDPv6 Service Provider : 2 : 23 : 2 : 17 : 0x22609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 RSVP UDP Service Provider : 2 : 2 : 2 : 17 : 0x22609 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 9d60a9e0-337a-11d0-bd88-0000c082e69a 
 MSAFD Irda [IrDA] : 2 : 26 : 1 : 1 : 0x20006 : 0x8 : %SystemRoot%\system32\mswsock.dll :  : 3972523d-2af1-11d1-b655-00805f3642cc
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.

**Comment by eric-bixby** [comment]
I ran it on FF 51.0.1 on Mac, Win7, and Win10, but no crash.  I cannot tell from the report where it is actually crashing.  I would expect to see a crash address and reason as describe on this page:
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Crash_reporting/Understanding_crash_reports

**Comment by eric-bixby** [comment]
@mattsplats: Could you send me the raw dump?  Do an "about:crashes", select the crash, click on the "raw dump" (you'll need to be signed-in), download the report and then email it to me directly:
ebixby@yahoo.com

**Comment by Taurean75** [comment]
I'm having the same problem.  I'll send you a raw dump.

**Comment by ivysrono** [comment]
https://crash-stats.mozilla.com/report/index/2e61788f-5f36-4a6e-a731-007b22170220

I'm Chinese.

**Comment by EMLVIRUS** [comment]
I'm so sorry. I shall be responsible for such crash. It seems that @ivysrono crash led by processing zh-CN locale file, which is submitted by me. @ivysrono , could you try to install this addon from English AMO (try English version of this addon) to see if crash happens again?

**Comment by ivysrono** [comment]
@EMLVIRUS https://crash-stats.mozilla.com/report/index/36e4017c-5b49-4477-9929-be95e2170220
I have change my firefox to en-US and reinstall autosort addon.

**Comment by eric-bixby** [comment]
@EMLVIRUS: I don't know that it's the Chinese translation yet.

I did a diff between release 2.10.9 and 2.10.10; there were other changes that I had made and forgot about.  I did some code reformatting to fix some ESLint findings (a JavaScript format checker).

Could someone please try creating a new Firefox profile and re-installing the add-on?  Maybe your old preferences are not compatible with the new release.

I'm still trying to reproduce the crash on my machines.  Based on the provided crash reports, it's seems to be a combination of the internationalization component and reading preferences.

**Comment by EMLVIRUS** [comment]
Em, I don't know what you have done. pull request #43 is only add a Chinese translate file. but @ivysrono seems to be more complex than I thought

**Comment by ivysrono** [comment]
Strange.
I create a new profile and install the addon, No Crash...

**Comment by eric-bixby** [comment]
Great. It might seem strange, but that's what I was counting on. That means the problem is in the code I changed for preference handling. I wasn't crashing because I'm using the default settings.

**Comment by yrdjuret** [comment]
Do you want more crash reports?

**Comment by eric-bixby** [comment]
No thanks.  I have enough crash reports.

I'll post a test version as soon as I have a fix.

**Comment by eric-bixby** [comment]
I'm able to reproduce the bug.  It's the "then-sort-by" preference.  The data-type got changed from integer to string.  If you changed this preference, prior to upgrading to 2.10.10, then Firefox crashes on startup with 2.10.10 installed.

**Comment by eric-bixby** [comment]
I have a fix, if anyone wants to try using an unsigned release:
https://github.com/antoyo/auto-sort-bookmarks/releases/tag/v2.10.11

To test this, he's my recommended test procedure:
1) Uninstall the existing version
2) Reboot (this will remove default preferences)
3) Enter "about:config", then filter on "extensions.sortbookmarks@bouanto"
4) Right-click on each remaining pref or just then_sort_by and select "reset"
5) Enter "about:debugging", then temp load v2.10.11
6) Enter "about:config", then filter on "extensions.sortbookmarks@bouanto"
7) Verify that then_sort_by has a type of Integer and a value of -1.

I also update the code so that if the type is still a String, it will convert the value to an integer.

**Comment by Taurean75** [comment]
How do you install an unveiled add-on?

**Comment by eric-bixby** [comment]
1. Enter "about:debugging" into the address bar.
2. Select "Load Temporary Add-on" button.
3. Browse to .xpi file and select "Open" button.

**Comment by Taurean75** [comment]
Thanks,, Eric.

No crashes with the new version.
