### ISSUE TITLE
[Off topic] New add-on idea: Auto-title bookmarks

### ISSUE THREAD

**Issue by davidhedlund** [antoyo/auto-sort-bookmarks#49]
Allows bookmark properties to be set to the current page's properties or to clipboard text quickly via the context menu. - https://addons.mozilla.org/en-US/firefox/addon/update-bookmark/

That add-on is unfortunately dead.

**Comment by eric-bixby** [comment]
Another add-on is exactly what I was going to recommend. I don't know if you tried it yet, but after nine years, that add-on probably doesn't work. 

In my humble opinion (iMHO), add-ons should stick to a strict scope. Do one thing and (hopefully) do that one thing we'll.

Therefore, I don't think it makes sense to add that feature to the ASB add-on. However, I'd like to encourage to to contact that developer to show interest and maybe they will update it. If not, you should try forking that project and updating it yourself (assuming the author doesn't mind).

**Comment by eric-bixby** [comment]
Also, it should like you like to keep the web page author's title.  Personally, I almost never do this.  I use the original title as a starting point.  I end up changing it to something that is shorter and more meaningful to me.

**Comment by davidhedlund** [comment]
@eric-bixby  thank you for your answers.
