### ISSUE TITLE
Feature Request: Add Whitelist and/or allow Manual Override

### ISSUE THREAD

**Issue by tberneman** [antoyo/auto-sort-bookmarks#52]
Just one of my example s is I have 3 folders I like to see in this order "Daily, Weekly, Monthly". The problem is autosort changes it to "Daily, Monthly, Weekly".

I would like to either manually move Weekly up and have autosort remember that and not change it on subsequent sorts. This would also mean that you would have to have a way to turn it back off on a case by case basis.

Another option would be to have a Whitelist (aka: ignore) feature where I could add those 3 folders and Autosort would leave them alone.

Another solution (or additional feature) is to allow me to use REGEX (and/or simple text) to whitelist bookmarks. I could either then specify to white list those folders individually or I could put an Underscore "_" character before each one and whitelist it with a REGEX expression.

**Comment by eric-bixby** [comment]
There's already an exclude folder option.  Did you try that?

Under preferences, Folder to sort, select "Configure", click on "Bookmarks Menu" to expand it.
Keep expanding until you get to the folder you want to exclude, then uncheck them to exclude them from being sorted.  Except, I think you want these three folders in a separate folder, then set that new folder to be excluded.

**Comment by tberneman** [comment]
I will check that out.

Thanks for the response!

Tim :o]
