### ISSUE TITLE
Sorting does not work in Firefox 36

### ISSUE THREAD

**Issue by heftig** [antoyo/auto-sort-bookmarks#8]
Sorting does not work in Firefox 36 as getFolderReadonly was removed, see https://bugzilla.mozilla.org/show_bug.cgi?id=1068671 .

**Comment by blackwind** [comment]
With Firefox 36 now in beta, this now affects far more users, and in six weeks, your add-on will be broken for everyone. Can you take a look at this sooner rather than later, @antoyo?

**Comment by antoyo** [comment]
This bug should be fixed in version 2.7.
Thanks for reporting it.
