### ISSUE TITLE
Only sort bookmarks in selected folders

### ISSUE THREAD

**Issue by Sagehorn** [antoyo/auto-sort-bookmarks#9]
..Is one of the most important features to me. I've got thousands of bookmarks but I'm not interested in sorting all of them. I only want to sort bookmarks of forum threads where I'm active in (by visiting date), thats all.. So please add an option to select only single folders. My firefox is loading as hell otherwise.. And there seems no alternative on the addon market..

**Comment by antoyo** [comment]
This feature has been added in version 2.8.
